### PR TITLE
Update CTA link and shorten URL

### PR DESCRIPTION
**Pull request by morgangiraud**
I've made small update to the website that I think could be valuable for the newcomer:
- Update the link of both "start contributing" CTA to the Docs repository (ending on the list of repo is not that useful for a newcomer to know what to do next)
- Add the shorten link referenced in #13 
- Update the width of the console so the link fit on one line

### CODE REVIEW

**Comment by cereallarceny** [comment]
Understood @morgangiraud.  We're rolling out some massive breaking changes to the website, including a Wordpress-powered back-end.  Some of your changes may not apply.  With that said, can we defer this PR until after those changes are done to ensure a good merge?

**Comment by morgangiraud** [comment]
No problem, I guess it's related the fact that all the hardcoded data will be removed.
Anyway, if my PR has still some relevancy after the update, feel free to ping me so I can rebase it etc.

**Comment by cereallarceny** [comment]
Terrific.  That remains to be seen.  I believe there's likely some CSS that we could share from your PR here.  As for the CTA link, let's keep an open discussion about what the best place for that to go is.  I'm open to it being on the docs repo.  I think for now that's best, but @iamtrask may feel otherwise.  Not sure.

**Comment by morgangiraud** [comment]
I Agree, the probable other candidate is the tutorials repo.
In the end, I really think it should at least link to a README where potential next steps are explained

**Comment by cereallarceny** [comment]
This can be closed due to the addition of a Wordpress back-end.  Things can be entered there.

**Pull request closed without merging**
